## Vespidae

### Polistes canadensis
Comparison with Dinoponera ant, also a simple society. Slight difference between phenotype at the level of transcription network. 
**Methylation** no difference between phenotypes
**Genome** CEGMA: 97%.
**Transcriptome** low levels of differentiation between castes
**Reference**: **Patalano**, S., Vlasova, A., Wyatt, C., Ewels, P., Camara, F., Ferreira, P.G., Asher, C.L., Jurkowski, T.P., Segonds-Pichon, A., Bachman, M. and González-Navarrete, I., **2015**. Molecular signatures of plastic phenotypes in two eusocial insect species with simple societies. Proceedings of the National Academy of Sciences, 112(45), pp.13970-13975.

### Polistes dominula
Primitively eusocial wasp
**Methylation** patterns are surprisingly low, when compared with other social species with caste differentiation. One main gene associated with methylation (Dnmt3) is lost. Which mechanisms underlie caste differentiation, if not methylation?
**Genome** N50: 1.6 Mb; CEGMA: 99.2%. 
**Transcriptome**: majority of genes are worker-biased
**Reference**: **Standage**, D.S., Berens, A.J., Glastad, K.M., Severin, A.J., Brendel, V.P. and Toth, A.L., **2016**. Genome, transcriptome and methylome sequencing of a primitively eusocial wasp reveal a greatly reduced DNA methylation system in a social insect. Molecular ecology, 25(8), pp.1769-1784.
